-- ============================================================================
--  ALAS · GESTIÓN DE ACUSES — setup completo para Supabase (proyecto DEDICADO)
--  Pegá TODO esto en: Supabase → SQL Editor → Run.
--  Idempotente: se puede volver a correr sin romper nada.
--
--  Incluye: schema + RLS anon + trigger del Nº (AC-0001) + datos de arranque
--  (repartidores y unos clientes/artículos demo para probar ya).
--  Los catálogos reales (miles de clientes/artículos de SAP) se importan
--  después por CSV en Table Editor (ver README de pasos).
--
--  La anon key es pública por diseño (RLS anon, gate = SSO ALAS).
--  NUNCA usar service_role en el cliente.
-- ============================================================================

-- ─────────────────────────── CATÁLOGOS ───────────────────────────
create table if not exists clientes (
  cod_cliente text primary key,
  nombre      text,
  ruc         text,
  direccion   text,
  ciudad      text,
  zona        text,
  telefono    text,
  canal       text,
  cond_venta  text,
  vendedor    text
);
create index if not exists idx_clientes_nombre on clientes (lower(nombre));

create table if not exists articulos (
  material    text primary key,   -- Material_SAP
  descripcion text,               -- Descr_SAP
  um          text,               -- UM_SAP
  status      text,               -- Status_SAP
  jerarquia   text                -- Jerarquia_SAP
);
create index if not exists idx_articulos_descr on articulos (lower(descripcion));

-- ─────────────────────────── REPARTIDORES ───────────────────────────
create table if not exists repartidores (
  id      bigint generated by default as identity primary key,
  codigo  text,
  nombre  text not null,
  activo  boolean not null default true
);

-- ─────────────────────────── ACUSE (cabecera) ───────────────────────────
create table if not exists acuses (
  id                bigint generated by default as identity primary key,
  nro_acuse         text unique,
  cod_cliente       text,
  cliente_nombre    text,
  cliente_ruc       text,
  cliente_direccion text,
  cliente_ciudad    text,
  cliente_telefono  text,
  zona              text,
  estado            text not null default 'Pendiente',
  fecha_emision     date not null,
  fecha_entrega     date,
  repartidor_id     bigint references repartidores(id),
  repartidor_nombre text,
  observacion       text,
  usuario           text,
  activo            boolean not null default true,
  created_at        timestamptz not null default now()
);
create index if not exists idx_acuses_created on acuses (created_at desc);
create index if not exists idx_acuses_estado  on acuses (estado);
create index if not exists idx_acuses_emision on acuses (fecha_emision);
create index if not exists idx_acuses_cliente on acuses (cod_cliente);
create index if not exists idx_acuses_repart  on acuses (repartidor_id);

-- ─────────────────────────── DETALLE ───────────────────────────
create table if not exists acuse_detalle (
  id             bigint generated by default as identity primary key,
  acuse_id       bigint not null references acuses(id) on delete cascade,
  cod_mercaderia text not null,
  descripcion    text,
  cantidad       numeric not null default 0,
  um             text,
  nota           text
);
create index if not exists idx_detalle_acuse on acuse_detalle (acuse_id);

-- ─────────────────────────── HISTORIAL DE ESTADOS ───────────────────────────
create table if not exists acuse_historial (
  id          bigint generated by default as identity primary key,
  acuse_id    bigint not null references acuses(id) on delete cascade,
  estado      text not null,
  usuario     text,
  observacion text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_historial_acuse on acuse_historial (acuse_id);

-- ─────────────────────────── LOG DE ACCIONES ───────────────────────────
create table if not exists acuse_log (
  id          bigint generated by default as identity primary key,
  acuse_id    bigint references acuses(id) on delete set null,
  accion      text not null,
  usuario     text,
  observacion text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_log_created on acuse_log (created_at desc);

-- ─────────────────────────── Nº automático AC-0001 ───────────────────────────
create or replace function acuses_set_nro()
returns trigger language plpgsql as $$
begin
  if new.nro_acuse is null or new.nro_acuse = '' then
    new.nro_acuse := 'AC-' || lpad(new.id::text, 4, '0');
  end if;
  return new;
end $$;
drop trigger if exists trg_acuses_nro on acuses;
create trigger trg_acuses_nro before insert on acuses
  for each row execute function acuses_set_nro();

-- ─────────────────────────── RLS (anon all) ───────────────────────────
alter table clientes        enable row level security;
alter table articulos       enable row level security;
alter table repartidores    enable row level security;
alter table acuses          enable row level security;
alter table acuse_detalle   enable row level security;
alter table acuse_historial enable row level security;
alter table acuse_log       enable row level security;

do $$
declare t text;
begin
  foreach t in array array['clientes','articulos','repartidores','acuses','acuse_detalle','acuse_historial','acuse_log']
  loop
    execute format('drop policy if exists anon_all on %I', t);
    execute format('create policy anon_all on %I for all to anon using (true) with check (true)', t);
  end loop;
end $$;

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- ============================================================================
--  DATOS DE ARRANQUE (editables / borrables)
-- ============================================================================

-- Repartidores (cambiá por los reales). No duplica si ya existen por nombre.
insert into repartidores (codigo, nombre)
select v.codigo, v.nombre
from (values
  ('REP001','Amilcar García'),
  ('REP002','Jonathan Peralta'),
  ('REP003','Lisandro López'),
  ('REP004','Juan Balmori'),
  ('REP005','Ignacio Vera')
) as v(codigo, nombre)
where not exists (select 1 from repartidores r where upper(r.nombre) = upper(v.nombre));

-- Clientes demo (borralos cuando importes los reales de SAP)
insert into clientes (cod_cliente, nombre, ruc, direccion, ciudad, zona, telefono) values
  ('C1001','ATLANTIC S.A.E.','80012345-6','Av. Artigas 1200','Asunción','Central','021 555 100'),
  ('C1002','ZR DISTRIBUIDORA','80023456-7','Ruta 2 km 18','San Lorenzo','Central','021 555 200'),
  ('C1003','FORTLEV INDUSTRIA','80034567-8','Parque Industrial','Luque','Central','021 555 300'),
  ('C1004','ORION S.R.L.','80045678-9','Calle Última 456','Capiatá','Interior','0228 555 400')
on conflict (cod_cliente) do nothing;

-- Artículos demo (borralos cuando importes los reales de SAP)
insert into articulos (material, descripcion, um, status) values
  ('100023','Caño PVC 100mm','UN','Activo'),
  ('100048','Codo PVC 90°','UN','Activo'),
  ('100112','Cemento bolsa 50kg','BOL','Activo'),
  ('100205','Hierro 8mm x 12m','UN','Activo')
on conflict (material) do nothing;

-- ── (Opcional) Realtime, si querés cambios en vivo entre usuarios ──
do $$
begin
  begin alter publication supabase_realtime add table acuses;
  exception when duplicate_object then null; when undefined_object then null; end;
end $$;
