-- ============================================================================
--  ALAS · Apartado ACUSES — esquema Supabase (proyecto DEDICADO nuevo)
--  Correr en el SQL Editor del proyecto Supabase que crees para Acuses.
--
--  Migración del sistema ACUSE (Node+Express+MySQL) a Supabase.
--  Patrón: RLS abierta a anon (el gate real es el SSO ALAS en la UI), igual
--  que los otros módulos vanilla del ecosistema. La anon key es pública por
--  diseño. NUNCA usar service_role en el cliente.
--
--  Estados canónicos: 'Pendiente' · 'En Reparto' · 'Entregado' · 'Anulado'
-- ============================================================================

-- ── Catálogos (se importan desde SAP: clientes y artículos) ──────────────────
create table if not exists clientes (
  cod_cliente text primary key,
  nombre      text,
  ruc         text,
  direccion   text,
  ciudad      text,
  zona        text,
  telefono    text,
  canal       text,
  cond_venta  text,
  vendedor    text
);
create index if not exists idx_clientes_nombre on clientes (lower(nombre));

create table if not exists articulos (
  material    text primary key,   -- Material_SAP
  descripcion text,               -- Descr_SAP
  um          text,               -- UM_SAP
  status      text,               -- Status_SAP
  jerarquia   text                -- Jerarquia_SAP
);
create index if not exists idx_articulos_descr on articulos (lower(descripcion));

-- ── Repartidores ─────────────────────────────────────────────────────────────
create table if not exists repartidores (
  id      bigint generated by default as identity primary key,
  codigo  text,
  nombre  text not null,
  activo  boolean not null default true
);

-- ── Acuse (cabecera) ─────────────────────────────────────────────────────────
create table if not exists acuses (
  id                bigint generated by default as identity primary key,
  nro_acuse         text unique,                    -- AC-0001 (se completa tras insertar)
  cod_cliente       text,
  cliente_nombre    text,                           -- snapshot para el listado (sin join)
  cliente_ruc       text,
  cliente_direccion text,
  cliente_ciudad    text,
  cliente_telefono  text,
  zona              text,
  estado            text not null default 'Pendiente',
  fecha_emision     date not null,
  fecha_entrega     date,
  repartidor_id     bigint references repartidores(id),
  repartidor_nombre text,                           -- snapshot
  observacion       text,
  usuario           text,
  activo            boolean not null default true,
  created_at        timestamptz not null default now()
);
create index if not exists idx_acuses_created  on acuses (created_at desc);
create index if not exists idx_acuses_estado   on acuses (estado);
create index if not exists idx_acuses_emision  on acuses (fecha_emision);
create index if not exists idx_acuses_cliente  on acuses (cod_cliente);
create index if not exists idx_acuses_repart   on acuses (repartidor_id);

-- ── Detalle del acuse ────────────────────────────────────────────────────────
create table if not exists acuse_detalle (
  id             bigint generated by default as identity primary key,
  acuse_id       bigint not null references acuses(id) on delete cascade,
  cod_mercaderia text not null,
  descripcion    text,
  cantidad       numeric not null default 0,
  um             text,
  nota           text
);
create index if not exists idx_detalle_acuse on acuse_detalle (acuse_id);

-- ── Historial de estados ─────────────────────────────────────────────────────
create table if not exists acuse_historial (
  id          bigint generated by default as identity primary key,
  acuse_id    bigint not null references acuses(id) on delete cascade,
  estado      text not null,
  usuario     text,
  observacion text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_historial_acuse on acuse_historial (acuse_id);

-- ── Log de acciones (auditoría) ──────────────────────────────────────────────
create table if not exists acuse_log (
  id          bigint generated by default as identity primary key,
  acuse_id    bigint references acuses(id) on delete set null,
  accion      text not null,   -- CREAR · EDITAR · CAMBIO_ESTADO · ANULAR · IMPRIMIR
  usuario     text,
  observacion text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_log_created on acuse_log (created_at desc);

-- ── Nº de acuse automático (AC-0001) al insertar ─────────────────────────────
create or replace function acuses_set_nro()
returns trigger language plpgsql as $$
begin
  if new.nro_acuse is null or new.nro_acuse = '' then
    new.nro_acuse := 'AC-' || lpad(new.id::text, 4, '0');
  end if;
  return new;
end $$;

drop trigger if exists trg_acuses_nro on acuses;
create trigger trg_acuses_nro before insert on acuses
  for each row execute function acuses_set_nro();

-- ── RLS: lectura/escritura anon (control fino = SSO en la UI) ────────────────
alter table clientes         enable row level security;
alter table articulos        enable row level security;
alter table repartidores     enable row level security;
alter table acuses           enable row level security;
alter table acuse_detalle    enable row level security;
alter table acuse_historial  enable row level security;
alter table acuse_log        enable row level security;

do $$
declare t text;
begin
  foreach t in array array['clientes','articulos','repartidores','acuses','acuse_detalle','acuse_historial','acuse_log']
  loop
    execute format('drop policy if exists anon_all on %I', t);
    execute format('create policy anon_all on %I for all to anon using (true) with check (true)', t);
  end loop;
end $$;

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
