-- ============================================================================
--  ALAS · Apartado CALENDARIO DE TAREAS — esquema Supabase (proyecto DEDICADO)
--  Correr en el SQL Editor del proyecto Supabase que crees para el Calendario.
--
--  Patrón: RLS abierta a anon (gate real = SSO ALAS en la UI). La anon key es
--  pública por diseño. NUNCA usar service_role en el cliente.
--
--  Estados: 'Pendiente' · 'En curso' · 'Hecho'
--  Prioridad: 'BAJA' · 'NORMAL' · 'ALTA'
-- ============================================================================

create table if not exists tareas (
  id          bigint generated by default as identity primary key,
  titulo      text not null,
  descripcion text,
  fecha       date not null,
  hora        time,
  responsable text,
  prioridad   text not null default 'NORMAL',
  estado      text not null default 'Pendiente',
  usuario     text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists idx_tareas_fecha  on tareas (fecha);
create index if not exists idx_tareas_estado on tareas (estado);

-- Mantener updated_at
create or replace function tareas_touch()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;
drop trigger if exists trg_tareas_touch on tareas;
create trigger trg_tareas_touch before update on tareas
  for each row execute function tareas_touch();

-- ── RLS: lectura/escritura anon (control fino = SSO en la UI) ────────────────
alter table tareas enable row level security;
drop policy if exists anon_all on tareas;
create policy anon_all on tareas for all to anon using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant all on tareas to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- (Opcional) Realtime para ver cambios en vivo entre usuarios
do $$
begin
  begin alter publication supabase_realtime add table tareas;
  exception when duplicate_object then null; when undefined_object then null; end;
end $$;
