-- ============================================================================
--  ALAS · CALENDARIO DE TAREAS — instalación en el proyecto de Acuses
--  Proyecto: fdcumrdbnrjpbfbrxqiw
--  Correr en Supabase → SQL Editor. Una sola vez.
--
--  ┌──────────────────────────────────────────────────────────────────────┐
--  │ USAR ESTE ARCHIVO, NO calendario_schema.sql                          │
--  │                                                                      │
--  │ `calendario_schema.sql` fue escrito para un proyecto Supabase        │
--  │ dedicado y termina con:                                              │
--  │     create policy anon_all on tareas for all to anon using (true)    │
--  │ Eso volvería a abrir lo que cerró seguridad_01_permisos_minimos.sql. │
--  │                                                                      │
--  │ Este archivo crea la misma tabla pero con permisos explícitos, y no  │
--  │ toca ninguna tabla de Acuses.                                        │
--  └──────────────────────────────────────────────────────────────────────┘
--
--  Reemplaza correr por separado:
--    · db/calendario_schema.sql
--    · db/calendario_orden_fix.sql
--
--  Es idempotente: se puede correr de nuevo sin romper nada.
-- ============================================================================

begin;

-- ── 1. Tabla ────────────────────────────────────────────────────────────────
create table if not exists tareas (
  id          bigint generated by default as identity primary key,
  titulo      text not null,
  descripcion text,
  fecha       date not null,
  hora        time,
  responsable text,
  deposito    text,          -- Depósito Central · Fábrica · Depósito Luque Sanber
  prioridad   text not null default 'NORMAL',   -- BAJA · NORMAL · ALTA
  estado      text not null default 'Pendiente',-- Pendiente · En curso · Hecho
  usuario     text,          -- quién la cargó (nombre del SSO)
  orden       int,           -- orden manual DENTRO de (deposito, fecha)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ── 1b. Reconciliar una tabla `tareas` preexistente ─────────────────────────
--  `create table if not exists` NO agrega columnas si la tabla ya estaba. Si
--  existe una versión vieja con otro esquema, sin esto el índice de más abajo
--  falla con: ERROR 42703: column "hora" does not exist.
--  Se agregan TODAS las columnas, no solo las que uno cree que faltan.
alter table tareas add column if not exists titulo      text;
alter table tareas add column if not exists descripcion text;
alter table tareas add column if not exists fecha       date;
alter table tareas add column if not exists hora        time;
alter table tareas add column if not exists responsable text;
alter table tareas add column if not exists deposito    text;
alter table tareas add column if not exists prioridad   text not null default 'NORMAL';
alter table tareas add column if not exists estado      text not null default 'Pendiente';
alter table tareas add column if not exists usuario     text;
alter table tareas add column if not exists orden       int;
alter table tareas add column if not exists created_at  timestamptz not null default now();
alter table tareas add column if not exists updated_at  timestamptz not null default now();

--  `titulo` y `fecha` deben ser NOT NULL, pero forzarlo revienta si la tabla
--  vieja ya tiene filas con esos campos vacíos. Se intenta y, si no se puede,
--  se avisa en vez de cortar todo el script.
do $$
declare c text;
begin
  foreach c in array array['titulo', 'fecha'] loop
    begin
      execute format('alter table tareas alter column %I set not null', c);
    exception when others then
      raise notice 'No se pudo poner NOT NULL en tareas.% (%). Revisá las filas con ese campo vacío.', c, sqlerrm;
    end;
  end loop;
end $$;

-- ── 2. Índices ──────────────────────────────────────────────────────────────
--  El principal acompaña exactamente el orden con que la app consulta:
--  fecha primero, después el orden manual del día.
create index if not exists idx_tareas_dep_fecha_orden
  on tareas (deposito, fecha, orden nulls last, hora nulls first, id);
create index if not exists idx_tareas_fecha  on tareas (fecha);
create index if not exists idx_tareas_estado on tareas (estado);

-- ── 3. updated_at automático ────────────────────────────────────────────────
create or replace function tareas_touch()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;

drop trigger if exists trg_tareas_touch on tareas;
create trigger trg_tareas_touch before update on tareas
  for each row execute function tareas_touch();

-- ── 4. Reordenar atómico ────────────────────────────────────────────────────
--  Sin esto la app manda un PATCH por tarea al reordenar.
create or replace function reorder_tareas(p_ids bigint[], p_ordenes int[])
returns void
language plpgsql
as $$
begin
  if p_ids is null or p_ordenes is null then
    raise exception 'reorder_tareas: parámetros nulos' using errcode = '22004';
  end if;
  if array_length(p_ids, 1) is distinct from array_length(p_ordenes, 1) then
    raise exception 'reorder_tareas: los arrays deben tener el mismo largo' using errcode = '22023';
  end if;

  update tareas t
     set orden = v.orden
    from (select unnest(p_ids) as id, unnest(p_ordenes) as orden) v
   where t.id = v.id;
end;
$$;

-- ── 5. Permisos ─────────────────────────────────────────────────────────────
--  Nota honesta: `tareas` necesita las cuatro operaciones porque la app deja
--  borrar. O sea que para esta tabla el permiso queda igual de amplio que
--  antes — la diferencia es que ahora está escrito explícitamente y no se
--  extiende al resto del proyecto con un `grant all on all tables`.
--  Para cerrarlo de verdad hay que pasar a borrado lógico (ver el final).
alter table tareas enable row level security;

drop policy if exists anon_all       on tareas;
drop policy if exists anon_select    on tareas;
drop policy if exists anon_insert    on tareas;
drop policy if exists anon_update    on tareas;
drop policy if exists anon_delete    on tareas;

create policy anon_select on tareas for select to anon, authenticated using (true);
create policy anon_insert on tareas for insert to anon, authenticated with check (true);
create policy anon_update on tareas for update to anon, authenticated using (true);
create policy anon_delete on tareas for delete to anon, authenticated using (true);

-- Solo sobre `tareas`: NO usar `grant all on all tables in schema public`,
-- que es lo que dejaba el schema original y abriría las tablas de Acuses.
grant select, insert, update, delete on tareas to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

commit;

-- ── 6. Realtime (fuera de la transacción) ───────────────────────────────────
--  Permite que dos operarios con dos teléfonos se vean los cambios en vivo.
do $$
begin
  begin alter publication supabase_realtime add table tareas;
  exception when duplicate_object then null; when undefined_object then null; end;
end $$;

-- ============================================================================
--  VERIFICACIÓN
-- ============================================================================

-- (a) La tabla existe y está vacía:
select count(*) as tareas_cargadas from tareas;

-- (b) Los permisos quedaron como se esperaba:
select tablename, policyname, cmd, roles
  from pg_policies
 where schemaname = 'public' and tablename = 'tareas'
 order by cmd;

-- (c) Las tablas de Acuses siguen cerradas (no debe aparecer DELETE en
--     acuses, clientes, articulos, repartidores, acuse_historial ni acuse_log):
select table_name, string_agg(privilege_type, ', ' order by privilege_type) as permisos
  from information_schema.role_table_grants
 where table_schema = 'public' and grantee = 'anon'
 group by table_name
 order by table_name;

-- ============================================================================
--  DESPUÉS DE CORRER ESTO
--
--  1. Cargar en Vercel → Settings → Environment Variables:
--       VITE_CAL_SUPABASE_URL       https://fdcumrdbnrjpbfbrxqiw.supabase.co
--       VITE_CAL_SUPABASE_ANON_KEY  <la anon key>
--     y volver a desplegar (la clave se compila dentro del bundle).
--
--  2. Lo mismo en .env.local para desarrollo.
--
--  3. Abrir el Calendario: si el cartel amarillo "No hay conexión con la base"
--     desapareció y la lista está vacía, quedó conectado. Las 5 tareas de
--     ejemplo ("Revisar recepción de hierros", etc.) ya no deberían aparecer.
--
--  PENDIENTE
--  Con la anon key todavía se puede borrar cualquier tarea desde afuera de la
--  app. Se cierra con borrado lógico: agregar `deleted_at timestamptz`, que la
--  app filtre `deleted_at is null`, y quitarle el DELETE a anon.
-- ============================================================================
