-- ============================================================================
--  ALAS · SEGURIDAD paso 1 — permiso mínimo por tabla
--  Proyecto: fdcumrdbnrjpbfbrxqiw  (Acuses + Calendario)
--  Correr en Supabase → SQL Editor.
--
--  ┌──────────────────────────────────────────────────────────────────────┐
--  │ LEER ESTO ANTES DE CORRERLO                                          │
--  │                                                                      │
--  │ Esto NO convierte el sistema en seguro. Mientras el front use solo   │
--  │ la anon key y no haya una identidad autenticada, la base no puede    │
--  │ distinguir entre "la app" y "alguien con curl": presentan exactamente │
--  │ la misma credencial. Ninguna policy puede separarlos.                 │
--  │                                                                      │
--  │ Lo que sí hace: reducir el daño posible. Hoy cualquiera con la anon   │
--  │ key puede BORRAR todo. Después de esto no puede borrar acuses, ni     │
--  │ tocar los catálogos, ni alterar el historial ni la auditoría.         │
--  │                                                                      │
--  │ El arreglo de fondo es darle identidad al front (ver paso 2).         │
--  └──────────────────────────────────────────────────────────────────────┘
--
--  Los permisos salen de lo que el front realmente ejecuta:
--
--    tabla             insert  update  delete   →  permiso que queda
--    ─────────────────────────────────────────────────────────────────
--    clientes             -       -       -        select
--    articulos            -       -       -        select
--    repartidores         1       -       -        select, insert
--    acuses               2       7       -        select, insert, update
--    acuse_detalle        4       -       2        select, insert, delete
--    acuse_historial      9       -       -        select, insert
--    acuse_log           10       -       -        select, insert
--    tareas               1       2       1        select, insert, update, delete
--
--  Es reversible: al final del archivo está el SQL para volver atrás.
-- ============================================================================

begin;

-- ── 1. Sacar el permiso general ─────────────────────────────────────────────
--  El schema original hacía `grant all on all tables ... to anon`. Eso da
--  incluso TRUNCATE. Lo quitamos y repartimos de nuevo, tabla por tabla.
--
--  ⚠️ SOLO sobre las tablas de Acuses y Calendario, NOMBRADAS UNA POR UNA.
--  La versión anterior hacía `revoke all on all tables in schema public`, sin
--  saber que este proyecto también aloja las 19 tablas de Incidencias y tres
--  de la app de calendario anterior. Les sacó el GRANT a todas y solo se lo
--  devolvió a las de acá: Incidencias quedó con sus policies pero sin poder
--  leer nada (en Postgres hacen falta las dos cosas). Ver seguridad_02.
revoke all on
  clientes, articulos, repartidores, acuses, acuse_detalle,
  acuse_historial, acuse_log, tareas
from anon, authenticated;

-- Las columnas `generated by default as identity` necesitan las secuencias.
grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ── 2. Permiso mínimo por tabla ─────────────────────────────────────────────
-- Catálogos SAP: el front nunca los escribe (la importación va por el panel).
grant select                          on clientes        to anon, authenticated;
grant select                          on articulos       to anon, authenticated;

grant select, insert                  on repartidores    to anon, authenticated;

-- Sin DELETE: anular un acuse es un UPDATE de `estado`, no un borrado.
grant select, insert, update          on acuses          to anon, authenticated;

-- Sin UPDATE: al editar, el front borra las líneas y las vuelve a insertar.
grant select, insert, delete          on acuse_detalle   to anon, authenticated;

-- Append-only: la auditoría se agrega, nunca se corrige ni se borra.
grant select, insert                  on acuse_historial to anon, authenticated;
grant select, insert                  on acuse_log       to anon, authenticated;

-- Calendario: sigue necesitando borrar (ver "Pendiente" al final).
grant select, insert, update, delete  on tareas          to anon, authenticated;

-- ── 3. Policies granulares en lugar de `for all using (true)` ───────────────
--  Los GRANT de arriba ya alcanzan, pero las policies lo dejan explícito y
--  protegen si alguien vuelve a correr un `grant all` por error.
do $$
declare
  t     text;
  ops   text;
  op    text;
  plan  text[][] := array[
    ['clientes',        'select'],
    ['articulos',       'select'],
    ['repartidores',    'select,insert'],
    ['acuses',          'select,insert,update'],
    ['acuse_detalle',   'select,insert,delete'],
    ['acuse_historial', 'select,insert'],
    ['acuse_log',       'select,insert'],
    ['tareas',          'select,insert,update,delete']
  ];
  i int;
begin
  for i in 1 .. array_length(plan, 1) loop
    t   := plan[i][1];
    ops := plan[i][2];

    if to_regclass('public.' || t) is null then
      raise notice 'tabla % no existe en este proyecto, se omite', t;
      continue;
    end if;

    execute format('alter table %I enable row level security', t);
    -- Fuera la policy abierta original.
    execute format('drop policy if exists anon_all on %I', t);

    foreach op in array string_to_array(ops, ',') loop
      execute format('drop policy if exists %I on %I', 'anon_' || op, t);
      if op = 'insert' then
        execute format('create policy %I on %I for insert to anon, authenticated with check (true)',
                       'anon_' || op, t);
      else
        execute format('create policy %I on %I for %s to anon, authenticated using (true)',
                       'anon_' || op, t, op);
      end if;
    end loop;
  end loop;
end $$;

commit;

-- ============================================================================
--  VERIFICACIÓN — qué puede hacer `anon` en cada tabla ahora
-- ============================================================================
select
  c.relname                                                        as tabla,
  c.relrowsecurity                                                 as rls,
  string_agg(distinct p.cmd, ', ' order by p.cmd)                  as policies,
  string_agg(distinct g.privilege_type, ', ' order by g.privilege_type) as grants
from pg_class c
join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
left join pg_policies p on p.tablename = c.relname and p.schemaname = 'public'
left join information_schema.role_table_grants g
       on g.table_name = c.relname and g.table_schema = 'public' and g.grantee = 'anon'
where c.relkind = 'r'
group by c.relname, c.relrowsecurity
order by c.relname;

-- Esperado: ninguna fila con DELETE en `acuses`, `clientes`, `articulos`,
-- `repartidores`, `acuse_historial` ni `acuse_log`.

-- ============================================================================
--  PENDIENTE (no lo resuelve este archivo)
--
--  1. `tareas` todavía se puede borrar con la anon key. Se cierra pasando a
--     borrado lógico: agregar `deleted_at timestamptz`, que la app filtre
--     `deleted_at is null` y que "Eliminar" haga UPDATE en vez de DELETE.
--
--  2. Cualquiera con la anon key sigue pudiendo LEER todo y CREAR registros.
--     Eso solo se corta con identidad real en el front — paso 2.
--
--  3. Este archivo no toca el proyecto de Incidencias. Ahí sigue abierta la
--     escalada de privilegios de `ensure_user` (permite crear un usuario con
--     rol ADMIN desde el cliente). Va en su propio archivo.
-- ============================================================================

-- ============================================================================
--  VOLVER ATRÁS  (si algo se rompe en producción, correr esto)
--
--    grant all on all tables in schema public to anon, authenticated;
--    do $$ declare t text;
--    begin
--      foreach t in array array['clientes','articulos','repartidores','acuses',
--                               'acuse_detalle','acuse_historial','acuse_log','tareas']
--      loop
--        if to_regclass('public.'||t) is null then continue; end if;
--        execute format('drop policy if exists anon_select on %I', t);
--        execute format('drop policy if exists anon_insert on %I', t);
--        execute format('drop policy if exists anon_update on %I', t);
--        execute format('drop policy if exists anon_delete on %I', t);
--        execute format('create policy anon_all on %I for all to anon using (true) with check (true)', t);
--      end loop;
--    end $$;
-- ============================================================================
